    $(document).ready(function()
    {
        $("#includes").load('includes.html'),
        $("#navbar").load('navbar.html'),
        $("#about").load('about.html'),
        $("#portfolio").load('portfolio.html'),
        $("#footer").load('footer.html'),
        $("#contact").load('contact.html')
    })
